"""initial_schema

Revision ID: 46d411819996
Revises: 
Create Date: 2026-06-23 11:33:47.506943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d411819996'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=False),
    sa.Column('folder_path', sa.String(length=256), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('made_for_kids', sa.Boolean(), nullable=False),
    sa.Column('preset_title_template', sa.String(length=256), nullable=True),
    sa.Column('preset_description_template', sa.Text(), nullable=True),
    sa.Column('preset_tags', sa.JSON(), nullable=True),
    sa.Column('preset_social_links', sa.JSON(), nullable=True),
    sa.Column('thumbnail_style_name', sa.String(length=64), nullable=True),
    sa.Column('thumbnail_style_prompt', sa.Text(), nullable=True),
    sa.Column('thumbnail_style_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('gcp_project_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_genre'), 'channels', ['genre'], unique=False)
    op.create_index(op.f('ix_channels_folder_path'), 'channels', ['folder_path'], unique=False)
    op.create_index(op.f('ix_channels_is_active'), 'channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_channels_auto_approve'), 'channels', ['auto_approve'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('EDITOR', 'SUPERVISOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notification_prefs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('channel_credentials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('gcp_project_id', sa.String(length=128), nullable=False),
    sa.Column('oauth_credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('oauth_refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('oauth_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_credentials_is_active'), 'channel_credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_channel_credentials_oauth_token_expiry'), 'channel_credentials', ['oauth_token_expiry'], unique=False)
    op.create_table('gcp_projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('client_secret_path', sa.String(length=256), nullable=False),
    sa.Column('quota_limit', sa.Integer(), nullable=False),
    sa.Column('quota_used', sa.Integer(), nullable=False),
    sa.Column('last_reset', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'QUOTA_EXCEEDED', name='gcpprojectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gcp_projects_last_reset'), 'gcp_projects', ['last_reset'], unique=False)
    op.create_index(op.f('ix_gcp_projects_project_id'), 'gcp_projects', ['project_id'], unique=True)
    op.create_index(op.f('ix_gcp_projects_status'), 'gcp_projects', ['status'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('screenshot_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'PREPARING', 'STAGING', 'APPROVED', 'QUEUED', 'UPLOADING', 'UPLOADED', 'FAILED', 'DISCARDED', 'ERROR', name='videostatus'), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('youtube_privacy', sa.Enum('PRIVATE', 'PUBLIC', 'UNLISTED', name='youtubeprivacy'), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('current_title', sa.String(length=100), nullable=True),
    sa.Column('current_description', sa.Text(), nullable=True),
    sa.Column('current_tags', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_created_at'), 'videos', ['created_at'], unique=False)
    op.create_index(op.f('ix_videos_scheduled_time'), 'videos', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=False)
    op.create_table('analytics_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('hours_since_publish', sa.Integer(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('views_gained', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('dislikes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avd_seconds', sa.Integer(), nullable=True),
    sa.Column('avd_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('traffic_sources', sa.JSON(), nullable=True),
    sa.Column('demographics', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_records_avd_seconds'), 'analytics_records', ['avd_seconds'], unique=False)
    op.create_index(op.f('ix_analytics_records_channel_id'), 'analytics_records', ['channel_id'], unique=False)
    op.create_index(op.f('ix_analytics_records_ctr'), 'analytics_records', ['ctr'], unique=False)
    op.create_index(op.f('ix_analytics_records_recorded_at'), 'analytics_records', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_analytics_records_video_id'), 'analytics_records', ['video_id'], unique=False)
    op.create_index(op.f('ix_analytics_records_youtube_video_id'), 'analytics_records', ['youtube_video_id'], unique=False)
    op.create_table('metadata_drafts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('generation_type', sa.Enum('AUTO', 'MANUAL_EDIT', 'AI_SUGGESTION', name='metadatagenerationtype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('supervisor_feedback', sa.Text(), nullable=True),
    sa.Column('ab_test_group', sa.Enum('CONTROL', 'VARIANT_A', 'VARIANT_B', name='abtestgroup'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_drafts_ab_test_group'), 'metadata_drafts', ['ab_test_group'], unique=False)
    op.create_index(op.f('ix_metadata_drafts_is_approved'), 'metadata_drafts', ['is_approved'], unique=False)
    op.create_table('notification_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_type', sa.Enum('VIDEO_READY', 'UPLOAD_COMPLETE', 'UPLOAD_FAILED', 'DAILY_REPORT', 'ANOMALY_ALERT', 'COPYRIGHT_ALERT', 'QUOTA_WARNING', 'SYSTEM_ALERT', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'DASHBOARD', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_history_notification_type'), 'notification_history', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_history_sent_at'), 'notification_history', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notification_history_status'), 'notification_history', ['status'], unique=False)
    op.create_index(op.f('ix_notification_history_user_id'), 'notification_history', ['user_id'], unique=False)
    op.create_table('performance_insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.Column('insight_type', sa.Enum('ANOMALY', 'SUGGESTION', 'AB_TEST_RESULT', 'TREND', 'MILESTONE', name='insighttype'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='insightseverity'), nullable=False),
    sa.Column('metric_type', sa.String(length=32), nullable=True),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metric_average', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('sent_to_telegram', sa.Boolean(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_insights_channel_id'), 'performance_insights', ['channel_id'], unique=False)
    op.create_index(op.f('ix_performance_insights_created_at'), 'performance_insights', ['created_at'], unique=False)
    op.create_index(op.f('ix_performance_insights_insight_type'), 'performance_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_performance_insights_is_read'), 'performance_insights', ['is_read'], unique=False)
    op.create_index(op.f('ix_performance_insights_severity'), 'performance_insights', ['severity'], unique=False)
    op.create_index(op.f('ix_performance_insights_video_id'), 'performance_insights', ['video_id'], unique=False)
    op.create_table('queue_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='queuetaskstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_index(op.f('ix_queue_tasks_celery_task_id'), 'queue_tasks', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_queue_tasks_scheduled_at'), 'queue_tasks', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_queue_tasks_status'), 'queue_tasks', ['status'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_channel_id'), 'system_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_event_type'), 'system_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_request_id'), 'system_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_system_logs_service'), 'system_logs', ['service'], unique=False)
    op.create_index(op.f('ix_system_logs_video_id'), 'system_logs', ['video_id'], unique=False)
    op.create_table('thumbnail_drafts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('style_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('selection_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_drafts_is_selected'), 'thumbnail_drafts', ['is_selected'], unique=False)
    op.create_index(op.f('ix_thumbnail_drafts_style_name'), 'thumbnail_drafts', ['style_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnail_drafts_style_name'), table_name='thumbnail_drafts')
    op.drop_index(op.f('ix_thumbnail_drafts_is_selected'), table_name='thumbnail_drafts')
    op.drop_table('thumbnail_drafts')
    op.drop_index(op.f('ix_system_logs_video_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_service'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_request_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_event_type'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_channel_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_queue_tasks_status'), table_name='queue_tasks')
    op.drop_index(op.f('ix_queue_tasks_scheduled_at'), table_name='queue_tasks')
    op.drop_index(op.f('ix_queue_tasks_celery_task_id'), table_name='queue_tasks')
    op.drop_table('queue_tasks')
    op.drop_index(op.f('ix_performance_insights_video_id'), table_name='performance_insights')
    op.drop_index(op.f('ix_performance_insights_severity'), table_name='performance_insights')
    op.drop_index(op.f('ix_performance_insights_is_read'), table_name='performance_insights')
    op.drop_index(op.f('ix_performance_insights_insight_type'), table_name='performance_insights')
    op.drop_index(op.f('ix_performance_insights_created_at'), table_name='performance_insights')
    op.drop_index(op.f('ix_performance_insights_channel_id'), table_name='performance_insights')
    op.drop_table('performance_insights')
    op.drop_index(op.f('ix_notification_history_user_id'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_status'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_sent_at'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_notification_type'), table_name='notification_history')
    op.drop_table('notification_history')
    op.drop_index(op.f('ix_metadata_drafts_is_approved'), table_name='metadata_drafts')
    op.drop_index(op.f('ix_metadata_drafts_ab_test_group'), table_name='metadata_drafts')
    op.drop_table('metadata_drafts')
    op.drop_index(op.f('ix_analytics_records_youtube_video_id'), table_name='analytics_records')
    op.drop_index(op.f('ix_analytics_records_video_id'), table_name='analytics_records')
    op.drop_index(op.f('ix_analytics_records_recorded_at'), table_name='analytics_records')
    op.drop_index(op.f('ix_analytics_records_ctr'), table_name='analytics_records')
    op.drop_index(op.f('ix_analytics_records_channel_id'), table_name='analytics_records')
    op.drop_index(op.f('ix_analytics_records_avd_seconds'), table_name='analytics_records')
    op.drop_table('analytics_records')
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_scheduled_time'), table_name='videos')
    op.drop_index(op.f('ix_videos_created_at'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_gcp_projects_status'), table_name='gcp_projects')
    op.drop_index(op.f('ix_gcp_projects_project_id'), table_name='gcp_projects')
    op.drop_index(op.f('ix_gcp_projects_last_reset'), table_name='gcp_projects')
    op.drop_table('gcp_projects')
    op.drop_index(op.f('ix_channel_credentials_oauth_token_expiry'), table_name='channel_credentials')
    op.drop_index(op.f('ix_channel_credentials_is_active'), table_name='channel_credentials')
    op.drop_table('channel_credentials')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')

    op.drop_index(op.f('ix_channels_auto_approve'), table_name='channels')
    op.drop_index(op.f('ix_channels_is_active'), table_name='channels')
    op.drop_index(op.f('ix_channels_folder_path'), table_name='channels')
    op.drop_index(op.f('ix_channels_genre'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
